package com.deepreps.core.domain.model

/**
 * Result of the 4-level plan generation fallback chain.
 *
 * The variant indicates which level produced the plan, enabling analytics
 * tracking and UI messaging (e.g., "Generated by AI" vs "Offline baseline").
 */
sealed interface PlanResult {
    val plan: GeneratedPlan?

    /** AI provider returned a plan successfully. */
    data class AiGenerated(override val plan: GeneratedPlan) : PlanResult

    /** AI unavailable; a previously cached plan was used. */
    data class Cached(override val plan: GeneratedPlan) : PlanResult

    /** No AI and no cache; baseline heuristic plan generated offline. */
    data class Baseline(override val plan: GeneratedPlan) : PlanResult

    /** All fallback levels exhausted; user must enter sets manually. */
    data object Manual : PlanResult {
        override val plan: GeneratedPlan? = null
    }
}
